[package]
name = "sdl_rust"
version = "0.1.0"
authors = ["Konrad Szymoniak <szymoniak.konrad@gmail.com>"]
edition = "2018"

[dependencies.sdl2]
version = "0.32"
default-features = false
features = ["gfx"]